### ISSUE TITLE
Feature request (stdout all data + errors)

### ISSUE THREAD

**Issue by ghost** [saeeddhqan/evine#2]
Hello Folks!
Thanks to all who's made such a great tool.
Just wanted to request feature: That's would be great to implement some _Logging capability_ meaning: (all runtime data (urls, emails, network, all_urls etc)) + errors to target file.

Something like this:
./evine -url https://target.tld/ -sitemap --robots -depth 100 -delay 800 -timeout 10 -wayback **_--logfile=/tmp/alllogs.txt_**

Thanks in advance and keep up!

Cheers

**Comment by saeeddhqan** [comment]
I'll work on it(logger). If you need to save all the info, just run `all` command, then save the response

Thanks!

**Comment by ghost** [comment]
> I'll work on it(logger). If you need to save all the info, just run `all` command, then save the response
> 
> Thanks!

  Hello!

Thank you very much!)

**Comment by saeeddhqan** [comment]
Check the new version out.

**Comment by ghost** [comment]
Kudos!) Thank you!
