### ISSUE TITLE
[Question] Possible to dump the HTML out?

### ISSUE THREAD

**Issue by CharlieDigital** [saeeddhqan/evine#3]
Really cool tool; just wondering if it's possible to dump out the actual HTML?

If I understand it correctly here, it is extracting specific types of content (URL, emails, etc.)

But how do I extract/dump the raw underlying HTML?

**Comment by saeeddhqan** [comment]
Which format do you want for the HTML file to be?

**Comment by CharlieDigital** [comment]
Just normal text/UTF-8 :)

**Comment by saeeddhqan** [comment]
Ok,
Will do that in a free time :).
